---
title: "Figure and table"
output: 
  Grmd::docx_document:
    fig_caption: TRUE
    force_captions: TRUE
---

Figure and table
================

```{r Data_prep, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(warning=FALSE,
                      message=FALSE,
                      echo=FALSE,
                      dev="png", dev.args=list(type="cairo"), # The png device
                      # Change to dev="postscript" if you want the EPS-files
                      # for submitting. Also remove the dev.args() as the postscript
                      # doesn't accept the type="cairo" argument.
                      error=FALSE)

# Evaluate the figure caption after the plot
knitr::opts_knit$set(eval.after='fig.cap',
                     root.dir ="../")

# Use the table counter that the htmlTable() provides
options(table_counter = TRUE)

# Use the figCapNo() with roman letters
options(fig_caption_no_roman = TRUE)
```

```{r Versions}
info <- sessionInfo()
r_ver <- paste(info$R.version$major, info$R.version$minor, sep=".")
```

```{r}
library(rms) # I use the cox regression from this package
library(boot) # The melanoma data set is used in this exampe
library(Gmisc) # Stuff I find convenient
library(Greg) # You need to get this from my GitHub see http://gforge.se/packages/
library(plyr)

load("Results/Names.rdata")
source("Scripts/Functions/simulate.R")
source("Scripts/Functions/figurize.R")
source("Scripts/Functions/table.R")

```


Figure
=======
```{r, echo=FALSE, warning=FALSE}
plot.Predict.functions()
```

```{r, echo=FALSE, warning=FALSE}
plot.Predict.occurrence.stand()
```

```{r, echo=FALSE, warning=FALSE}
plot.LifePredict.Ndmh.stand()
```

```{r, echo=FALSE, warning=FALSE}
plot.LifePredict.PNdmh_DBH.tree()
```

Table
=====

```{r, results='asis', cache=FALSE}
table <- PredLoss.criteria()
table[1:3]<- apply(table[1:3], 
                MARGIN = 2, 
                FUN = function(x) round(as.numeric(x), 
                                        digits=2))
htmlTable(table)
```

```{r, results='asis', cache=FALSE}
table <- synth.MCMC()
table[4:9] <- apply(table[4:9], 
                    MARGIN = 2, 
                    FUN = function(x) round( as.numeric(x), 
                                             digits = 2))
table[2:3] <- apply(table[2:3], MARGIN = 2, FUN=as.character)
# rgroup <- levels(as.factor(paste(table$Model, table$Param)))
# rgroup <- rgroup[ order(rgroup, decreasing = TRUE)]

htmlTable(table, rowname = FALSE)
```