---
title: "MCMC converge check"
author: "Cyrille Pupin"
date: "7 novembre 2014"
output: html_document
---

Check convergence of MCMC computer.

```{r, echo=FALSE}
rm(list=ls())
load("Results/Names.rdata")
```



```{r, echo=FALSE}
in.MCMC <- readRDS(file=paste( "Results/", 
                               paste(Names$Project,
                                     Names$Model[1],
                                     sep="_"),
                               ".rds",
                               sep="")) 
```

```{r}
print(in.MCMC$Raw)
```

```{r, echo=FALSE}
in.MCMC <- readRDS(file=paste( "Results/", 
                               paste(Names$Project,
                                     Names$Model[2],
                                     sep="_"),
                               ".rds",
                               sep="")) 
```

```{r}
print(in.MCMC$Raw)
```

```{r, echo=FALSE}
in.MCMC <- readRDS(file=paste( "Results/", 
                               paste(Names$Project,
                                     Names$Model[3],
                                     sep="_"),
                               ".rds",
                               sep="")) 
```

```{r}
print(in.MCMC$Raw)
```
